#include "../libs/Unity/src/unity.h"

extern void test_lex_simple_declaration(void);
extern void test_lex_string_literal(void);
extern void test_lex_control_flow(void);
extern void test_lex_function_declaration(void);
extern void test_lex_boolean_and_null_literals(void);
extern void test_lex_array_and_plus_equal(void);
extern void test_parse_variable_declarations(void);
extern void test_parse_assignment_statement(void);
extern void test_parse_if_else(void);
extern void test_parse_while_loop(void);
extern void test_parse_function_declaration(void);
extern void test_expression_precedence(void);
extern void test_parse_call_expression(void);
extern void test_parse_array_literal_and_index(void);
extern void test_parser_reports_error(void);
extern void test_compile_arithmetic_script(void);
extern void test_compile_if_else_script(void);
extern void test_compile_function_call_script(void);
extern void test_compile_while_loop_script(void);
extern void test_compile_string_concatenation_script(void);
extern void test_compile_array_literal_script(void);
extern void test_vm_arithmetic_addition(void);
extern void test_vm_global_roundtrip(void);
extern void test_vm_locals_and_control_flow(void);
extern void test_vm_arithmetic_subtract(void);
extern void test_vm_arithmetic_multiply(void);
extern void test_vm_arithmetic_divide(void);
extern void test_vm_comparison_greater(void);
extern void test_vm_comparison_less(void);
extern void test_vm_comparison_equal(void);
extern void test_vm_unary_not(void);
extern void test_vm_unary_negate(void);
extern void test_vm_boolean_literals(void);
extern void test_vm_null_literal(void);
extern void test_vm_string_literal(void);
extern void test_vm_string_concatenation(void);
extern void test_vm_build_and_index_array(void);
extern void test_vm_array_addition_appends(void);
extern void test_vm_function_call(void);
extern void test_vm_if_else(void);
extern void test_vm_runtime_error_call_non_function(void);
extern void test_vm_runtime_error_undefined_global(void);
extern void test_vm_global_string_roundtrip(void);
extern void test_vm_garbage_collection_reclaims_unreferenced_strings(void);

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_lex_simple_declaration);
    RUN_TEST(test_lex_string_literal);
    RUN_TEST(test_lex_control_flow);
    RUN_TEST(test_lex_function_declaration);
    RUN_TEST(test_lex_boolean_and_null_literals);
    RUN_TEST(test_lex_array_and_plus_equal);
    RUN_TEST(test_parse_variable_declarations);
    RUN_TEST(test_parse_assignment_statement);
    RUN_TEST(test_parse_if_else);
    RUN_TEST(test_parse_while_loop);
    RUN_TEST(test_parse_function_declaration);
    RUN_TEST(test_expression_precedence);
    RUN_TEST(test_parse_call_expression);
    RUN_TEST(test_parse_array_literal_and_index);
    RUN_TEST(test_parser_reports_error);
    RUN_TEST(test_compile_arithmetic_script);
    RUN_TEST(test_compile_if_else_script);
    RUN_TEST(test_compile_function_call_script);
    RUN_TEST(test_compile_while_loop_script);
    RUN_TEST(test_compile_string_concatenation_script);
    RUN_TEST(test_compile_array_literal_script);
    RUN_TEST(test_vm_arithmetic_addition);
    RUN_TEST(test_vm_global_roundtrip);
    RUN_TEST(test_vm_locals_and_control_flow);
    RUN_TEST(test_vm_arithmetic_subtract);
    RUN_TEST(test_vm_arithmetic_multiply);
    RUN_TEST(test_vm_arithmetic_divide);
    RUN_TEST(test_vm_comparison_greater);
    RUN_TEST(test_vm_comparison_less);
    RUN_TEST(test_vm_comparison_equal);
    RUN_TEST(test_vm_unary_not);
    RUN_TEST(test_vm_unary_negate);
    RUN_TEST(test_vm_boolean_literals);
    RUN_TEST(test_vm_null_literal);
    RUN_TEST(test_vm_string_literal);
    RUN_TEST(test_vm_string_concatenation);
    RUN_TEST(test_vm_build_and_index_array);
    RUN_TEST(test_vm_array_addition_appends);
    RUN_TEST(test_vm_function_call);
    RUN_TEST(test_vm_if_else);
    RUN_TEST(test_vm_runtime_error_call_non_function);
    RUN_TEST(test_vm_runtime_error_undefined_global);
    RUN_TEST(test_vm_global_string_roundtrip);
    RUN_TEST(test_vm_garbage_collection_reclaims_unreferenced_strings);
    return UNITY_END();
}